# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Test AuthEngine
        run: xcodebuild -workspace AuthApp.xcworkspace -scheme AuthEngine -sdk macosx -destination 'platform=macOS' test
        
      - name: Test AuthAppBusinessDomain
        run: xcodebuild -workspace AuthApp.xcworkspace -scheme AuthAppBusinessDomain -sdk macosx -destination 'platform=macOS' test
     
      - name: Build AuthiOSApp
        run: xcodebuild -workspace AuthApp.xcworkspace -scheme AuthiOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
     
        
